name: Michał Szajbe
description: Personal blog
meta_description: "Michał Szajbe - Blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://szajbe.pl"
google_analytics: "UA-70089577-1"
plugins: [jekyll-paginate]
fenced_code_blocks: true

url: "https://szajbe.pl"
author: "Michał Szajbe"
