name: Michał Szajbe
description: My dev blog
meta_description: "Michał Szajbe - Blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://szajbus.dev"
google_analytics: "UA-70089577-1"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
fenced_code_blocks: true

url: "https://szajbus.dev"
author: "Michał Szajbe"
twitter_handle: szajbus
disqus_shortname: michal-szajbe
repo_url: "https://github.com/szajbus/szajbus.github.io"
