title: Michał Szajbe
email: michal.szajbe@gmail.com
description: >-
  My personal space.
baseurl: ""
url: "https://szajbus.dev"
twitter_username: szajbus
github_username: szajbus
github_repo: szajbus/szajbus.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

collections:
  - education
  - jobs

theme_config:
  date_format: "%Y-%m-%d"
  human_date_format: "%b %d, %Y"
  job_date_format: "%b %Y"
